### ISSUE TITLE
add funtionality to the search filter

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#1]
When a user enter their skill it should only show the profiles which had the/those skills

**Comment by tplive** [comment]
I can work on this

**Comment by AnkitaMalik22** [comment]
@tplive all yours!

**Comment by tplive** [comment]
...is this really a student assignment I'm solving for you? 😉

Also, plz use the #hacktoberfest-accepted tag on the issues for them to eligible for Hacktoberfest. 😄

**Comment by AnkitaMalik22** [comment]
> ...is this really a student assignment I'm solving for you? 😉
> 
> Also, plz use the #hacktoberfest-accepted tag on the issues for them to eligible for Hacktoberfest. 😄

not a student assignment haha! but I'm happy to learn from you😄

**Comment by MadhushaPrasad** [comment]
can i assign for this

**Comment by AnkitaMalik22** [comment]
@tplive are you working on this ?

**Comment by tplive** [comment]
I don't have anything yet. Let someone else have it if they want. 😊

**Comment by AnkitaMalik22** [comment]
> I don't have anything yet. Let someone else have it if they want. 😊

Okay✌🏻

**Comment by AnkitaMalik22** [comment]
> can i assign for this

Assigned to You @MadhushaPrasad
