### ISSUE TITLE
Social icons not showing in dark mode 

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#22]
![Screenshot_20221012-165112](https://user-images.githubusercontent.com/80139836/195363408-ba3f2c70-327e-4769-be5e-51077894d71a.png)
![Screenshot_20221012-165155](https://user-images.githubusercontent.com/80139836/195363458-d67a1387-3045-488d-9026-0bafac9fb00f.png)

**Comment by i-m-karanagarwal** [comment]
Hy @AnkitaMalik22  I would like to work on this. Please assign it to me.

**Comment by AnkitaMalik22** [comment]
Assigned to You!

**Comment by i-m-karanagarwal** [comment]
Hy @AnkitaMalik22 I cannot spot the button to change the modes.

So How do I set the trigger to change colors?

**Comment by AnkitaMalik22** [comment]
> Hy @AnkitaMalik22 I cannot spot the button to change the modes.
> 
> So How do I set the trigger to change colors?

[]()https://github.com/AnkitaMalik22/devmate/issues/18
****Someone is working on this issue ! 
But you can change chrome's theme to dark / light and see the problem.
