### ISSUE TITLE
Add GitHub icon in footer

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#23]
### Replace vercel icon with GitHub icon 

- after clicking the GitHub icon should open this repository 
![Screenshot_20221012-194740~2](https://user-images.githubusercontent.com/80139836/195368735-937113a9-4c99-4fdd-b630-178038ed3f5f.png)

**Comment by SubhamChoudhury** [comment]
Hey @AnkitaMalik22, can I take this up?

**Comment by jsvigneshkanna** [comment]
I can do this

**Comment by AnkitaMalik22** [comment]
@

> Kindly assign this to me @AnkitaMalik22

SubhamChoudhury got to it first, sorry @Eazyisreal

**Comment by AnkitaMalik22** [comment]
> Hey @AnkitaMalik22, can I take this up?

All yours!
