### ISSUE TITLE
Make the title smaller for mob devices 

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#24]
![Screenshot_20221012-195654](https://user-images.githubusercontent.com/80139836/195383343-7ba63da1-f5e5-4123-926c-1efbb8e55aca.png)

**Comment by jsvigneshkanna** [comment]
@AnkitaMalik22 , please assign this to my name

**Comment by AnkitaMalik22** [comment]
> @AnkitaMalik22 , please assign this to my name

Done!
