### ISSUE TITLE
Add instruction to fetch dependencies to README

### ISSUE THREAD

**Issue by tplive** [AnkitaMalik22/devmate#5]
The README omits mentioning that you first have to run `npm i` to download the dependencies before you can run the dev server.

**Comment by i-m-karanagarwal** [comment]
Hy @AnkitaMalik22 I would like to work on this issue. Please assign it to me.

**Comment by AnkitaMalik22** [comment]
> Hy @AnkitaMalik22 I would like to work on this issue. Please assign it to me.

Done!
