### ISSUE TITLE
Add Scroll to Top Icon 

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#78]

**Comment by Igdtuwresource** [comment]
@AnkitaMalik22 please assign me and tell me in which repo i need to add scroll to top icon. I am full stack developer.

**Comment by AnkitaMalik22** [comment]
> @AnkitaMalik22 please assign me and tell me in which repo i need to add scroll to top icon. I am full stack developer.
- Offcourse on this repository!
- in this website -> [https://devmate.vercel.app/](https://devmate.vercel.app/)

**Comment by Igdtuwresource** [comment]
![image](https://user-images.githubusercontent.com/112039921/196985743-3f1cd925-62e7-478b-a21e-1f5486b20230.png)
Actually I am new to open source. So please tell which file from this repo?

**Comment by thecyberera** [comment]
Hii @AnkitaMalik22, I want to work on this issue.

**Comment by AnkitaMalik22** [comment]
> ![image](https://user-images.githubusercontent.com/112039921/196985743-3f1cd925-62e7-478b-a21e-1f5486b20230.png) Actually I am new to open source. So please tell which file from this repo?

fork the repo and clone it 
- then go through the code you'll understand
- if not then comment here 😊

**Comment by AnkitaMalik22** [comment]
> @AnkitaMalik22 please assign me and tell me in which repo i need to add scroll to top icon. I am full stack developer.

Have you worked on nextjs before?

**Comment by AnkitaMalik22** [comment]
Assigned to @thecyberera

**Comment by thecyberera** [comment]
> Assigned to @thecyberera

Thanks @AnkitaMalik22

**Comment by Ishikasaraf20** [comment]
hey @AnkitaMalik22 can you assign this issue to me i can make this work
