### ISSUE TITLE
Show No of Results

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#80]
- After selecting skills  add a line below the search bar **_(example : 10)_ Dev Profiles Found!**
- it should not show when no skill selected

**Comment by Vaishnavi-More** [comment]
Hey! Could you please let me know where we have to add line of code and from where to select skills since I am newbie I don't have much idea.

**Comment by harsh0620** [comment]
Hey @AnkitaMalik22 , Please assign me this task.

**Comment by AnkitaMalik22** [comment]
Assigned to @harsh0620
