### ISSUE TITLE
Problem in search!! nothing is visible in search list.

### ISSUE THREAD

**Issue by goodchai0** [AnkitaMalik22/devmate#9]
![1 08](https://user-images.githubusercontent.com/79858905/195170549-52fae8b5-8eff-489f-bd16-21fdacf741a3.png)

I want to correct this.

![1 09](https://user-images.githubusercontent.com/79858905/195170559-144aee1f-cf75-4a16-a70d-5820bcca4af1.png)

Please, assign this task to me under hacktoberfest 2022 @AnkitaMalik22 .

**Comment by goodchai0** [comment]
Please put hacktober labels in your repo.

**Comment by AnkitaMalik22** [comment]
Assigned to you @goodchai0

**Comment by AnkitaMalik22** [comment]
https://github.com/AnkitaMalik22/devmate/pull/16#issue-1405583433
