### ISSUE TITLE
Improve the UI of the number of profiles box 

### ISSUE THREAD

**Issue by AnkitaMalik22** [AnkitaMalik22/devmate#94]
![Screenshot_20221026-171751.png](https://user-images.githubusercontent.com/80139836/198018505-0b8ce111-871d-4988-8467-90d9299a5225.png)

**Comment by NeilAn99** [comment]
Hi, I would like to work on this.

**Comment by AnkitaMalik22** [comment]
Assigned to you @NeilAn99

**Comment by NeilAn99** [comment]
Hi, is the following design ok with you?
![image](https://user-images.githubusercontent.com/54966170/198254644-9ef89a73-2c5f-425f-ab8f-d9ff038f0ed3.png)
![image](https://user-images.githubusercontent.com/54966170/198255043-bafd06b4-37fd-4ebc-b220-99c0d8739f70.png)
When hovered, the box lights up a little.
